[package]
name = "dup-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["multipart", "blocking"] }
tokio = { version = "1.43.0", features = ["full"] }
futures = "0.3.31"
